server:
  port: 8080

spring:
  application:
    name: spring-ai-deepseek-function-demo
  ai:
    deepseek:
      api-key: ${DEEPSEEK_API_KEY:}
      chat:
        options:
          model: deepseek-chat
          temperature: 0.2

logging:
  level:
    com.ke.deepseektools.tools: INFO
